# Generated by Django 5.1.5 on 2026-08-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ToDoModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("head_line", models.CharField(blank=True, max_length=100, null=True)),
                ("title", models.TextField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "image_attched",
                    models.ImageField(blank=True, null=True, upload_to="user/image"),
                ),
            ],
        ),
    ]
